------------------------------复习------------------------------
一,基本前置概念
1,会话:浏览器和服务器之间的交流(请求和响应)
    http协议是无状态的,多次请求之间是没有关联的
cookie是浏览器端的存储空间
二,操作cookie
1)原生js操作
  设置:document.cookie='name=pp';
  获取:document.cookie,以字符串形式返回所有的cookie
2)jQuery,jQuery.cooke.js 
  设置:$.cookie()????????
3)php操作
设置:setcookie('key','value');
设置过期时间:setcookie('key','value',time()+天数*24小时*360)
删除?????????
四,cookie的特点
1)存储大小4k
2)cookie中的数据,会在请求的时候携带,携带在请求头中
3)同一个网站的多个页面可以共享
4)不同浏览器的cookie不能共享
5)cookie如果不设置过期时间,默认是会话级别,一关闭浏览器,就会销毁,可以设置过期时间
6)服务器端不能直接操作cookie,获取,获取的是请求头中携带的cookie数据;设置的是响应头,让浏览器自己设置;
session是服务器的存储空间
1,通过$_SESSION获取session,返回值是一个关联数组,使用之间必须session_start();
2,获取:$_SESSION 
3,设置:$_SESSION['key']='value';
4,删除:unset($_SESSION['key']);
5,清空所有:$_SESSION=[];
6,销毁session文件:session_destory();
7,获取sessionid:session_id 
五,工作原理,
  开启session之后,
  1)该用户是第一次访问(该用户cookie中没有sessionid),服务器会生成一个sessionid(随机字符串);
  2)根据sessionid创建session文件(文件名是sessionid),我们可以在session空间存储用户数据;
  3)自动设置响应头(set-cookie里面存了sessionid),将sessionid传递给浏览器端,
  4)浏览器端接收到响应,解析响应头,将sessionid设置到cookie中去
  5)第二次访问,cookie中的数据会在请求时携带,所以请求时携带了sessionid
  6)服务器端就可以根据sessionid找到对应的文件,读取用户数据
六,会话保持
1,用户登录成功,记录用户信息,session_start()
2,往session空间中存数据:$_SESSION['key'] = 'value';
3,用户第二次访问,我们直接从session空间中读取数据
4,延迟刷新的方法:
   header('refresh:几秒后;url=刷新的地址');
七,会话拦截
1,判断用户有没有sessionid,有用户信息,输出用户信息;如果没有用户信息,拦截到登录页
2,如果没有sessionid,直接拦截到登录页
八,实现退出思路
1,让用户清空cookie(清除cookie中存的sessionid,类似清空浏览器缓存);
2,服务器端,将该用户的session清空
session_destory();清空session数据;